export const COUNTRY_CODES = [
  { code: '+93', iso: 'af', label: '🇦🇫 +93 (Afghanistan)' },
  { code: '+358', iso: 'ax', label: '🇦🇽 +358 (Aland Islands)' },
  { code: '+355', iso: 'al', label: '🇦🇱 +355 (Albania)' },
  { code: '+213', iso: 'dz', label: '🇩🇿 +213 (Algeria)' },
  { code: '+1684', iso: 'as', label: '🇦🇸 +1684 (American Samoa)' },
  { code: '+376', iso: 'ad', label: '🇦🇩 +376 (Andorra)' },
  { code: '+244', iso: 'ao', label: '🇦🇴 +244 (Angola)' },
  { code: '+1264', iso: 'ai', label: '🇦🇮 +1264 (Anguilla)' },
  { code: '+672', iso: 'aq', label: '🇦🇶 +672 (Antarctica)' },
  { code: '+1268', iso: 'ag', label: '🇦🇬 +1268 (Antigua and Barbuda)' },
  { code: '+54', iso: 'ar', label: '🇦🇷 +54 (Argentina)' },
  { code: '+374', iso: 'am', label: '🇦🇲 +374 (Armenia)' },
  { code: '+297', iso: 'aw', label: '🇦🇼 +297 (Aruba)' },
  { code: '+61', iso: 'au', label: '🇦🇺 +61 (Australia)' },
  { code: '+43', iso: 'at', label: '🇦🇹 +43 (Austria)' },
  { code: '+994', iso: 'az', label: '🇦🇿 +994 (Azerbaijan)' },
  { code: '+1242', iso: 'bs', label: '🇧🇸 +1242 (Bahamas)' },
  { code: '+973', iso: 'bh', label: '🇧🇭 +973 (Bahrain)' },
  { code: '+880', iso: 'bd', label: '🇧🇩 +880 (Bangladesh)' },
  { code: '+1246', iso: 'bb', label: '🇧🇧 +1246 (Barbados)' },
  { code: '+375', iso: 'by', label: '🇧🇾 +375 (Belarus)' },
  { code: '+32', iso: 'be', label: '🇧🇪 +32 (Belgium)' },
  { code: '+501', iso: 'bz', label: '🇧🇿 +501 (Belize)' },
  { code: '+229', iso: 'bj', label: '🇧🇯 +229 (Benin)' },
  { code: '+1441', iso: 'bm', label: '🇧🇲 +1441 (Bermuda)' },
  { code: '+975', iso: 'bt', label: '🇧🇹 +975 (Bhutan)' },
  { code: '+591', iso: 'bo', label: '🇧🇴 +591 (Bolivia)' },
  { code: '+599', iso: 'bq', label: '🇧🇶 +599 (Bonaire)' },
  { code: '+387', iso: 'ba', label: '🇧🇦 +387 (Bosnia and Herzegovina)' },
  { code: '+267', iso: 'bw', label: '🇧🇼 +267 (Botswana)' },
  { code: '+55', iso: 'br', label: '🇧🇷 +55 (Brazil)' },
  { code: '+246', iso: 'io', label: '🇮🇴 +246 (British Indian Ocean Territory)' },
  { code: '+1284', iso: 'vg', label: '🇻🇬 +1284 (British Virgin Islands)' },
  { code: '+673', iso: 'bn', label: '🇧🇳 +673 (Brunei)' },
  { code: '+359', iso: 'bg', label: '🇧🇬 +359 (Bulgaria)' },
  { code: '+226', iso: 'bf', label: '🇧🇫 +226 (Burkina Faso)' },
  { code: '+257', iso: 'bi', label: '🇧🇮 +257 (Burundi)' },
  { code: '+855', iso: 'kh', label: '🇰🇭 +855 (Cambodia)' },
  { code: '+237', iso: 'cm', label: '🇨🇲 +237 (Cameroon)' },
  { code: '+1', iso: 'ca', label: '🇨🇦 +1 (Canada)' },
  { code: '+238', iso: 'cv', label: '🇨🇻 +238 (Cape Verde)' },
  { code: '+1345', iso: 'ky', label: '🇰🇾 +1345 (Cayman Islands)' },
  { code: '+236', iso: 'cf', label: '🇨🇫 +236 (Central African Republic)' },
  { code: '+235', iso: 'td', label: '🇹🇩 +235 (Chad)' },
  { code: '+56', iso: 'cl', label: '🇨🇱 +56 (Chile)' },
  { code: '+86', iso: 'cn', label: '🇨🇳 +86 (China)' },
  { code: '+61', iso: 'cx', label: '🇨🇽 +61 (Christmas Island)' },
  { code: '+61', iso: 'cc', label: '🇨🇨 +61 (Cocos Islands)' },
  { code: '+57', iso: 'co', label: '🇨🇴 +57 (Colombia)' },
  { code: '+269', iso: 'km', label: '🇰🇲 +269 (Comoros)' },
  { code: '+242', iso: 'cg', label: '🇨🇬 +242 (Congo)' },
  { code: '+243', iso: 'cd', label: '🇨🇩 +243 (DR Congo)' },
  { code: '+682', iso: 'ck', label: '🇨🇰 +682 (Cook Islands)' },
  { code: '+506', iso: 'cr', label: '🇨🇷 +506 (Costa Rica)' },
  { code: '+385', iso: 'hr', label: '🇭🇷 +385 (Croatia)' },
  { code: '+53', iso: 'cu', label: '🇨🇺 +53 (Cuba)' },
  { code: '+599', iso: 'cw', label: '🇨🇼 +599 (Curacao)' },
  { code: '+357', iso: 'cy', label: '🇨🇾 +357 (Cyprus)' },
  { code: '+420', iso: 'cz', label: '🇨🇿 +420 (Czech Republic)' },
  { code: '+45', iso: 'dk', label: '🇩🇰 +45 (Denmark)' },
  { code: '+253', iso: 'dj', label: '🇩🇯 +253 (Djibouti)' },
  { code: '+1767', iso: 'dm', label: '🇩🇲 +1767 (Dominica)' },
  { code: '+1809', iso: 'do', label: '🇩🇴 +1809 (Dominican Republic)' },
  { code: '+593', iso: 'ec', label: '🇪🇨 +593 (Ecuador)' },
  { code: '+20', iso: 'eg', label: '🇪🇬 +20 (Egypt)' },
  { code: '+503', iso: 'sv', label: '🇸🇻 +503 (El Salvador)' },
  { code: '+240', iso: 'gq', label: '🇬🇶 +240 (Equatorial Guinea)' },
  { code: '+291', iso: 'er', label: '🇪🇷 +291 (Eritrea)' },
  { code: '+372', iso: 'ee', label: '🇪🇪 +372 (Estonia)' },
  { code: '+251', iso: 'et', label: '🇪🇹 +251 (Ethiopia)' },
  { code: '+500', iso: 'fk', label: '🇫🇰 +500 (Falkland Islands)' },
  { code: '+298', iso: 'fo', label: '🇫🇴 +298 (Faroe Islands)' },
  { code: '+679', iso: 'fj', label: '🇫🇯 +679 (Fiji)' },
  { code: '+358', iso: 'fi', label: '🇫🇮 +358 (Finland)' },
  { code: '+33', iso: 'fr', label: '🇫🇷 +33 (France)' },
  { code: '+594', iso: 'gf', label: '🇬🇫 +594 (French Guiana)' },
  { code: '+689', iso: 'pf', label: '🇵🇫 +689 (French Polynesia)' },
  { code: '+241', iso: 'ga', label: '🇬🇦 +241 (Gabon)' },
  { code: '+220', iso: 'gm', label: '🇬🇲 +220 (Gambia)' },
  { code: '+995', iso: 'ge', label: '🇬🇪 +995 (Georgia)' },
  { code: '+49', iso: 'de', label: '🇩🇪 +49 (Germany)' },
  { code: '+233', iso: 'gh', label: '🇬🇭 +233 (Ghana)' },
  { code: '+350', iso: 'gi', label: '🇬🇮 +350 (Gibraltar)' },
  { code: '+30', iso: 'gr', label: '🇬🇷 +30 (Greece)' },
  { code: '+299', iso: 'gl', label: '🇬🇱 +299 (Greenland)' },
  { code: '+1473', iso: 'gd', label: '🇬🇩 +1473 (Grenada)' },
  { code: '+590', iso: 'gp', label: '🇬🇵 +590 (Guadeloupe)' },
  { code: '+1671', iso: 'gu', label: '🇬🇺 +1671 (Guam)' },
  { code: '+502', iso: 'gt', label: '🇬🇹 +502 (Guatemala)' },
  { code: '+44', iso: 'gg', label: '🇬🇬 +44 (Guernsey)' },
  { code: '+224', iso: 'gn', label: '🇬🇳 +224 (Guinea)' },
  { code: '+245', iso: 'gw', label: '🇬🇼 +245 (Guinea-Bissau)' },
  { code: '+592', iso: 'gy', label: '🇬🇾 +592 (Guyana)' },
  { code: '+509', iso: 'ht', label: '🇭🇹 +509 (Haiti)' },
  { code: '+504', iso: 'hn', label: '🇭🇳 +504 (Honduras)' },
  { code: '+852', iso: 'hk', label: '🇭🇰 +852 (Hong Kong)' },
  { code: '+36', iso: 'hu', label: '🇭🇺 +36 (Hungary)' },
  { code: '+354', iso: 'is', label: '🇮🇸 +354 (Iceland)' },
  { code: '+91', iso: 'in', label: '🇮🇳 +91 (India)' },
  { code: '+62', iso: 'id', label: '🇮🇩 +62 (Indonesia)' },
  { code: '+98', iso: 'ir', label: '🇮🇷 +98 (Iran)' },
  { code: '+964', iso: 'iq', label: '🇮🇶 +964 (Iraq)' },
  { code: '+353', iso: 'ie', label: '🇮🇪 +353 (Ireland)' },
  { code: '+44', iso: 'im', label: '🇮🇲 +44 (Isle of Man)' },
  { code: '+972', iso: 'il', label: '🇮🇱 +972 (Israel)' },
  { code: '+39', iso: 'it', label: '🇮🇹 +39 (Italy)' },
  { code: '+225', iso: 'ci', label: '🇨🇮 +225 (Ivory Coast)' },
  { code: '+1876', iso: 'jm', label: '🇯🇲 +1876 (Jamaica)' },
  { code: '+81', iso: 'jp', label: '🇯🇵 +81 (Japan)' },
  { code: '+44', iso: 'je', label: '🇯🇪 +44 (Jersey)' },
  { code: '+962', iso: 'jo', label: '🇯🇴 +962 (Jordan)' },
  { code: '+7', iso: 'kz', label: '🇰🇿 +7 (Kazakhstan)' },
  { code: '+254', iso: 'ke', label: '🇰🇪 +254 (Kenya)' },
  { code: '+686', iso: 'ki', label: '🇰🇮 +686 (Kiribati)' },
  { code: '+383', iso: 'xk', label: '🇽🇰 +383 (Kosovo)' },
  { code: '+965', iso: 'kw', label: '🇰🇼 +965 (Kuwait)' },
  { code: '+996', iso: 'kg', label: '🇰🇬 +996 (Kyrgyzstan)' },
  { code: '+856', iso: 'la', label: '🇱🇦 +856 (Laos)' },
  { code: '+371', iso: 'lv', label: '🇱🇻 +371 (Latvia)' },
  { code: '+961', iso: 'lb', label: '🇱🇧 +961 (Lebanon)' },
  { code: '+266', iso: 'ls', label: '🇱🇸 +266 (Lesotho)' },
  { code: '+231', iso: 'lr', label: '🇱🇷 +231 (Liberia)' },
  { code: '+218', iso: 'ly', label: '🇱🇾 +218 (Libya)' },
  { code: '+423', iso: 'li', label: '🇱🇮 +423 (Liechtenstein)' },
  { code: '+370', iso: 'lt', label: '🇱🇹 +370 (Lithuania)' },
  { code: '+352', iso: 'lu', label: '🇱🇺 +352 (Luxembourg)' },
  { code: '+853', iso: 'mo', label: '🇲🇴 +853 (Macau)' },
  { code: '+389', iso: 'mk', label: '🇲🇰 +389 (Macedonia)' },
  { code: '+261', iso: 'mg', label: '🇲🇬 +261 (Madagascar)' },
  { code: '+265', iso: 'mw', label: '🇲🇼 +265 (Malawi)' },
  { code: '+60', iso: 'my', label: '🇲🇾 +60 (Malaysia)' },
  { code: '+960', iso: 'mv', label: '🇲🇻 +960 (Maldives)' },
  { code: '+223', iso: 'ml', label: '🇲🇱 +223 (Mali)' },
  { code: '+356', iso: 'mt', label: '🇲🇹 +356 (Malta)' },
  { code: '+692', iso: 'mh', label: '🇲🇭 +692 (Marshall Islands)' },
  { code: '+596', iso: 'mq', label: '🇲🇶 +596 (Martinique)' },
  { code: '+222', iso: 'mr', label: '🇲🇷 +222 (Mauritania)' },
  { code: '+230', iso: 'mu', label: '🇲🇺 +230 (Mauritius)' },
  { code: '+262', iso: 'yt', label: '🇾🇹 +262 (Mayotte)' },
  { code: '+52', iso: 'mx', label: '🇲🇽 +52 (Mexico)' },
  { code: '+691', iso: 'fm', label: '🇫🇲 +691 (Micronesia)' },
  { code: '+373', iso: 'md', label: '🇲🇩 +373 (Moldova)' },
  { code: '+377', iso: 'mc', label: '🇲🇨 +377 (Monaco)' },
  { code: '+976', iso: 'mn', label: '🇲🇳 +976 (Mongolia)' },
  { code: '+382', iso: 'me', label: '🇲🇪 +382 (Montenegro)' },
  { code: '+1664', iso: 'ms', label: '🇲🇸 +1664 (Montserrat)' },
  { code: '+212', iso: 'ma', label: '🇲🇦 +212 (Morocco)' },
  { code: '+258', iso: 'mz', label: '🇲🇿 +258 (Mozambique)' },
  { code: '+95', iso: 'mm', label: '🇲🇲 +95 (Myanmar)' },
  { code: '+264', iso: 'na', label: '🇳🇦 +264 (Namibia)' },
  { code: '+674', iso: 'nr', label: '🇳🇷 +674 (Nauru)' },
  { code: '+977', iso: 'np', label: '🇳🇵 +977 (Nepal)' },
  { code: '+31', iso: 'nl', label: '🇳🇱 +31 (Netherlands)' },
  { code: '+687', iso: 'nc', label: '🇳🇨 +687 (New Caledonia)' },
  { code: '+64', iso: 'nz', label: '🇳🇿 +64 (New Zealand)' },
  { code: '+505', iso: 'ni', label: '🇳🇮 +505 (Nicaragua)' },
  { code: '+227', iso: 'ne', label: '🇳🇪 +227 (Niger)' },
  { code: '+234', iso: 'ng', label: '🇳🇬 +234 (Nigeria)' },
  { code: '+683', iso: 'nu', label: '🇳🇺 +683 (Niue)' },
  { code: '+850', iso: 'kp', label: '🇰🇵 +850 (North Korea)' },
  { code: '+1670', iso: 'mp', label: '🇲🇵 +1670 (Northern Mariana Islands)' },
  { code: '+47', iso: 'no', label: '🇳🇴 +47 (Norway)' },
  { code: '+968', iso: 'om', label: '🇴🇲 +968 (Oman)' },
  { code: '+92', iso: 'pk', label: '🇵🇰 +92 (Pakistan)' },
  { code: '+680', iso: 'pw', label: '🇵🇼 +680 (Palau)' },
  { code: '+970', iso: 'ps', label: '🇵🇸 +970 (Palestine)' },
  { code: '+507', iso: 'pa', label: '🇵🇦 +507 (Panama)' },
  { code: '+675', iso: 'pg', label: '🇵🇬 +675 (Papua New Guinea)' },
  { code: '+595', iso: 'py', label: '🇵🇾 +595 (Paraguay)' },
  { code: '+51', iso: 'pe', label: '🇵🇪 +51 (Peru)' },
  { code: '+63', iso: 'ph', label: '🇵🇭 +63 (Philippines)' },
  { code: '+48', iso: 'pl', label: '🇵🇱 +48 (Poland)' },
  { code: '+351', iso: 'pt', label: '🇵🇹 +351 (Portugal)' },
  { code: '+1787', iso: 'pr', label: '🇵🇷 +1787 (Puerto Rico)' },
  { code: '+974', iso: 'qa', label: '🇶🇦 +974 (Qatar)' },
  { code: '+262', iso: 're', label: '🇷🇪 +262 (Reunion)' },
  { code: '+40', iso: 'ro', label: '🇷🇴 +40 (Romania)' },
  { code: '+7', iso: 'ru', label: '🇷🇺 +7 (Russia)' },
  { code: '+250', iso: 'rw', label: '🇷🇼 +250 (Rwanda)' },
  { code: '+590', iso: 'bl', label: '🇧🇱 +590 (Saint Barthelemy)' },
  { code: '+290', iso: 'sh', label: '🇸🇭 +290 (Saint Helena)' },
  { code: '+1869', iso: 'kn', label: '🇰🇳 +1869 (Saint Kitts and Nevis)' },
  { code: '+1758', iso: 'lc', label: '🇱🇨 +1758 (Saint Lucia)' },
  { code: '+590', iso: 'mf', label: '🇲🇫 +590 (Saint Martin)' },
  { code: '+508', iso: 'pm', label: '🇵🇲 +508 (Saint Pierre and Miquelon)' },
  { code: '+1784', iso: 'vc', label: '🇻🇨 +1784 (Saint Vincent and the Grenadines)' },
  { code: '+685', iso: 'ws', label: '🇼🇸 +685 (Samoa)' },
  { code: '+378', iso: 'sm', label: '🇸🇲 +378 (San Marino)' },
  { code: '+239', iso: 'st', label: '🇸🇹 +239 (Sao Tome and Principe)' },
  { code: '+966', iso: 'sa', label: '🇸🇦 +966 (Saudi Arabia)' },
  { code: '+221', iso: 'sn', label: '🇸🇳 +221 (Senegal)' },
  { code: '+381', iso: 'rs', label: '🇷🇸 +381 (Serbia)' },
  { code: '+248', iso: 'sc', label: '🇸🇨 +248 (Seychelles)' },
  { code: '+232', iso: 'sl', label: '🇸🇱 +232 (Sierra Leone)' },
  { code: '+65', iso: 'sg', label: '🇸🇬 +65 (Singapore)' },
  { code: '+1721', iso: 'sx', label: '🇸🇽 +1721 (Sint Maarten)' },
  { code: '+421', iso: 'sk', label: '🇸🇰 +421 (Slovakia)' },
  { code: '+386', iso: 'si', label: '🇸🇮 +386 (Slovenia)' },
  { code: '+677', iso: 'sb', label: '🇸🇧 +677 (Solomon Islands)' },
  { code: '+252', iso: 'so', label: '🇸🇴 +252 (Somalia)' },
  { code: '+27', iso: 'za', label: '🇿🇦 +27 (South Africa)' },
  { code: '+82', iso: 'kr', label: '🇰🇷 +82 (South Korea)' },
  { code: '+211', iso: 'ss', label: '🇸🇸 +211 (South Sudan)' },
  { code: '+34', iso: 'es', label: '🇪🇸 +34 (Spain)' },
  { code: '+94', iso: 'lk', label: '🇱🇰 +94 (Sri Lanka)' },
  { code: '+249', iso: 'sd', label: '🇸🇩 +249 (Sudan)' },
  { code: '+597', iso: 'sr', label: '🇸🇷 +597 (Suriname)' },
  { code: '+47', iso: 'sj', label: '🇸🇯 +47 (Svalbard and Jan Mayen)' },
  { code: '+268', iso: 'sz', label: '🇸🇿 +268 (Swaziland)' },
  { code: '+46', iso: 'se', label: '🇸🇪 +46 (Sweden)' },
  { code: '+41', iso: 'ch', label: '🇨🇭 +41 (Switzerland)' },
  { code: '+963', iso: 'sy', label: '🇸🇾 +963 (Syria)' },
  { code: '+886', iso: 'tw', label: '🇹🇼 +886 (Taiwan)' },
  { code: '+992', iso: 'tj', label: '🇹🇯 +992 (Tajikistan)' },
  { code: '+255', iso: 'tz', label: '🇹🇿 +255 (Tanzania)' },
  { code: '+66', iso: 'th', label: '🇹🇭 +66 (Thailand)' },
  { code: '+670', iso: 'tl', label: '🇹🇱 +670 (Timor-Leste)' },
  { code: '+228', iso: 'tg', label: '🇹🇬 +228 (Togo)' },
  { code: '+690', iso: 'tk', label: '🇹🇰 +690 (Tokelau)' },
  { code: '+676', iso: 'to', label: '🇹🇴 +676 (Tonga)' },
  { code: '+1868', iso: 'tt', label: '🇹🇹 +1868 (Trinidad and Tobago)' },
  { code: '+216', iso: 'tn', label: '🇹🇳 +216 (Tunisia)' },
  { code: '+90', iso: 'tr', label: '🇹🇷 +90 (Turkey)' },
  { code: '+993', iso: 'tm', label: '🇹🇲 +993 (Turkmenistan)' },
  { code: '+1649', iso: 'tc', label: '🇹🇨 +1649 (Turks and Caicos Islands)' },
  { code: '+688', iso: 'tv', label: '🇹🇻 +688 (Tuvalu)' },
  { code: '+256', iso: 'ug', label: '🇺🇬 +256 (Uganda)' },
  { code: '+380', iso: 'ua', label: '🇺🇦 +380 (Ukraine)' },
  { code: '+971', iso: 'ae', label: '🇦🇪 +971 (United Arab Emirates)' },
  { code: '+44', iso: 'gb', label: '🇬🇧 +44 (United Kingdom)' },
  { code: '+1', iso: 'us', label: '🇺🇸 +1 (United States)' },
  { code: '+598', iso: 'uy', label: '🇺🇾 +598 (Uruguay)' },
  { code: '+998', iso: 'uz', label: '🇺🇿 +998 (Uzbekistan)' },
  { code: '+678', iso: 'vu', label: '🇻🇺 +678 (Vanuatu)' },
  { code: '+379', iso: 'va', label: '🇻🇦 +379 (Vatican City)' },
  { code: '+58', iso: 've', label: '🇻🇪 +58 (Venezuela)' },
  { code: '+84', iso: 'vn', label: '🇻🇳 +84 (Vietnam)' },
  { code: '+1284', iso: 'vg', label: '🇻🇬 +1284 (Virgin Islands (British))' },
  { code: '+1340', iso: 'vi', label: '🇻🇮 +1340 (Virgin Islands (US))' },
  { code: '+681', iso: 'wf', label: '🇼🇫 +681 (Wallis and Futuna)' },
  { code: '+212', iso: 'eh', label: '🇪🇭 +212 (Western Sahara)' },
  { code: '+967', iso: 'ye', label: '🇾🇪 +967 (Yemen)' },
  { code: '+260', iso: 'zm', label: '🇿🇲 +260 (Zambia)' },
  { code: '+263', iso: 'zw', label: '🇿🇼 +263 (Zimbabwe)' },
]
